# Generated by Django 4.2.6 on 2023-10-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_musician_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_date', models.DateField()),
                ('category', models.CharField(choices=[('S', 'SPORT'), ('M', 'MUSIC'), ('H', 'HEALTH'), ('F', 'FITNESS'), ('E', 'EDUCATION')], max_length=20)),
                ('rating', models.IntegerField(choices=[('very poor', 1), ('poor', 2), ('good', 3), ('very good', 4), ('excellent', 5)])),
                ('topic', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=3000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.author')),
            ],
        ),
    ]
